CREATE TABLE `MESSAGES` (
  `MESSAGE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID del Mensaje',
  `SENDER_ID` int(11) NOT NULL COMMENT 'ID del Remitente',
  `RECIPIENT_ID` int(11) NOT NULL COMMENT 'ID del Destinatario',
  `CONTENT` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Contenido del Mensaje',
  `TIMESTAMP` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y Hora del Mensaje',
  PRIMARY KEY (`MESSAGE_ID`),
  FOREIGN KEY (`SENDER_ID`) REFERENCES `ELEMENTO`(`ELEMENTO_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`RECIPIENT_ID`) REFERENCES `ELEMENTO`(`ELEMENTO_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabla de Mensajes';

CREATE TABLE `REACTIONS` (
  `REACTION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID de la Reacción',
  `MESSAGE_ID` int(11) NOT NULL COMMENT 'ID del Mensaje',
  `ELEMENTO_ID` int(11) NOT NULL COMMENT 'ID del Elemento que reaccionó',
  `REACTION_TYPE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de Reacción',
  `TIMESTAMP` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y Hora de la Reacción',
  PRIMARY KEY (`REACTION_ID`),
  FOREIGN KEY (`MESSAGE_ID`) REFERENCES `MESSAGES`(`MESSAGE_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`ELEMENTO_ID`) REFERENCES `ELEMENTO`(`ELEMENTO_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabla de Reacciones';
